"""LangChain integration for TraceLens."""

from __future__ import annotations

import time
from typing import Any

try:
    from langchain_core.callbacks import BaseCallbackHandler
except ImportError:
    BaseCallbackHandler = object  # fallback for typing if not installed

from tracelens.capture import TraceLensCapture


class TraceLensCallbackHandler(BaseCallbackHandler):
    """A callback handler that captures LangChain execution into TraceLens."""

    def __init__(self, tracer: TraceLensCapture) -> None:
        super().__init__()
        self.tracer = tracer
        self._run_data: dict[str, dict[str, Any]] = {}
        # Mapping from run_id to step_id generated by tracelens
        self._step_ids: dict[str, str] = {}

    def _start_run(
        self,
        run_id: str,
        name: str,
        step_type: str,
        input_text: str,
        parent_run_id: str | None = None,
        model: str | None = None,
        tool_name: str | None = None,
        tool_args: dict[str, Any] | None = None,
    ) -> None:
        """Record the start of a run."""
        # Convert run_id to string, and ensure it's a valid string. 
        # Using run_id directly as step_id guarantees the parent_step_id is known.
        step_id = str(run_id)
        self._step_ids[str(run_id)] = step_id
        
        self._run_data[str(run_id)] = {
            "name": name,
            "step_type": step_type,
            "input_text": input_text,
            "parent_run_id": str(parent_run_id) if parent_run_id else None,
            "model": model,
            "tool_name": tool_name,
            "tool_args": tool_args or {},
            "start_ms": time.time() * 1000,
        }

    def _end_run(self, run_id: str, output_text: str) -> None:
        """Finalize the run and add it to the tracer."""
        data = self._run_data.pop(str(run_id), None)
        if not data:
            return

        parent_run_id = data["parent_run_id"]
        parent_step_id = self._step_ids.get(parent_run_id) if parent_run_id else None

        duration_ms = time.time() * 1000 - data["start_ms"]

        self.tracer.add_step(
            agent_name=data["name"],
            step_type=data["step_type"],
            input_text=data["input_text"],
            output_text=output_text,
            parent_step_id=parent_step_id,
            model=data["model"],
            tool_name=data["tool_name"],
            tool_args=data["tool_args"],
            duration_ms=duration_ms,
            step_id=self._step_ids[str(run_id)],
            timestamp_ms=data["start_ms"],
        )

    def on_chain_start(
        self, serialized: dict[str, Any], inputs: dict[str, Any], *, run_id: Any, parent_run_id: Any | None = None, **kwargs: Any
    ) -> None:
        name = serialized.get("name", "chain")
        self._start_run(run_id, name, "router", str(inputs), parent_run_id)

    def on_chain_end(self, outputs: dict[str, Any], *, run_id: Any, **kwargs: Any) -> None:
        self._end_run(run_id, str(outputs))

    def on_llm_start(
        self, serialized: dict[str, Any], prompts: list[str], *, run_id: Any, parent_run_id: Any | None = None, **kwargs: Any
    ) -> None:
        name = serialized.get("name", "llm")
        model = kwargs.get("invocation_params", {}).get("model_name", None)
        self._start_run(run_id, name, "llm_call", "\\n".join(prompts), parent_run_id, model=model)

    def on_llm_end(self, response: Any, *, run_id: Any, **kwargs: Any) -> None:
        output_text = ""
        if hasattr(response, "generations") and response.generations:
            # Join generations if multiple
            output_text = "\\n".join(
                gen.text for gens in response.generations for gen in gens
            )
        self._end_run(run_id, output_text)

    def on_tool_start(
        self, serialized: dict[str, Any], input_str: str, *, run_id: Any, parent_run_id: Any | None = None, **kwargs: Any
    ) -> None:
        name = serialized.get("name", "tool")
        self._start_run(run_id, name, "tool", input_str, parent_run_id, tool_name=name)

    def on_tool_end(self, output: Any, *, run_id: Any, **kwargs: Any) -> None:
        self._end_run(run_id, str(output))

    def on_tool_error(self, error: BaseException, *, run_id: Any, **kwargs: Any) -> None:
        self._end_run(run_id, f"Error: {error}")
